### ISSUE TITLE
Possible API call change when overriding sc-parameter values

### ISSUE THREAD

**Issue by alosadagrande** [soukron/satapi#11]
We are using several API calls to update and set smart class parameters. Same parameters in 6.2 are working fine but in 6.3 we are facing an undefined method key for Array. Bellow the test we are executing:

[root@pv0il0610 ~]# bash -x satellite_api_call.sh

```
+ cURL POST /api/v2/puppetclasses/os_caj/smart_class_parameters/access_full_allowed_users/override_values
+ _method=POST
+ _url=/api/v2/puppetclasses/os_caj/smart_class_parameters/access_full_allowed_users/override_values
+ echo POST /api/v2/puppetclasses/os_caj/smart_class_parameters/access_full_allowed_users/override_values
+ '[' -f data.json ']'
+ cat data.json
+ '[' '!' -f data.json ']'
+ tee -a /tmp/curl.log
+ curl --basic --user 'srv_satapi_maqrem:Fj77$f12FDqt6D2D294Anf8$FFce<u' -k -H 'Accept: application/json;version=2' -H 'Content-Type: application/json' --data-binary @data.json -X POST -sS https://pv0il0610.cc0.example.es//api/v2/puppetclasses/os_caj/smart_class_parameters/access_full_allowed_users/override_values
{
  "error": {"message":"undefined method `key?' for #<Array:0x007f4dc2a28c00>"}
}
+ echo
```

where data.json is a hash which contains an array of elements in json format. Taking a look at apidoc on SAT 6.3 a hash is still required. Below the data.json where we are trying to update the smart_class_parameters:

`{"override_value": [{"value": "['']", "match": "kt_env=itg,hostgroup=2017dt5-1.310-caj-64"}, {"value": "['']", "match": "kt_env=pre,hostgroup=2017dt5-1.310-caj-64"}, {"value": "['']", "match": "kt_env=pro,hostgroup=2017dt5-1.310-caj-64"}]}`

**Comment by soukron** [comment]
Hi Alberto.
Thanks for sharing your findings.

Feel free to add a PR with the required changes if you find a solution suitable for 6.2 and 6.3. That would be awesome.

Regards,
Sergio
